accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views

# FIXME: accounts는 app_name을 쓰지 않습니다.
# app_name = ''


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(form_class=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('signup/', views.signup, name='signup'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
]

pnu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# FIXME: 이 코드는 RedirectView에 의해서 제거될 것입니다.
from django.shortcuts import redirect
def root(request):
    return redirect("shop:shop_list")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('weblog/', include('blog.urls')),
    path('shop/', include('shop.urls')),
    path('', root, name='root'),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_list, name='shop_list'),
    path('new/', views.shop_new, name='shop_new'),
    path('<int:pk>/edit/', views.shop_edit, name='shop_edit'),
    path('<int:pk>/', views.shop_detail, name='shop_detail',),
    path('items/', views.item_list, name='item_list'),
    path('items/<int:pk>/', views.item_detail, name='item_detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse


class Post(models.Model):
    # author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=100, validators=[MinLengthValidator(6)])
    content = models.TextField()
    ip = models.GenericIPAddressField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])
        # return reverse('blog:post_detail', kwargs={'pk': self.pk})
    
    @property
    def masked_ip(self):
        return '.'.join(self.ip.split('.')[:2] + ['*', '*'])

shop/models.py
from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse


class Shop(models.Model):
    name = models.CharField(max_length=100,
                            validators=[MinLengthValidator(5)])
    photo = models.ImageField(blank=True)  # Pillow 라이브러리 필수
    desc = models.TextField(blank=True)
    address = models.CharField(max_length=50, blank=True)

    def get_absolute_url(self):
        return reverse('shop:shop_detail', args=[self.pk])


class Item(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    price = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class LoginForm(AuthenticationForm):
    quiz = forms.IntegerField(label='3+3=?')

    def clean_quiz(self):
        quiz = self.cleaned_data.get('quiz')
        if quiz != 6:
            raise forms.ValidationError('땡~!')
        return quiz

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

shop/forms.py
from django import forms
from .models import Shop


class ShopForm(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'
        # widgets = {
        #     'address': ...,
        # }

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import redirect, render
from .forms import PostForm
from .models import Post


post_list = ListView.as_view(model=Post)


post_detail = DetailView.as_view(model=Post)


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            # return redirect('blog:post_list')
            # return redirect('blog:post_detail', post.pk)
            # 필히 post.get_absolute_url()이 구현되어있어야 합니다.
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

shop/views.py
# from django.views.generic import ListView
from django.shortcuts import redirect,render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Shop, Item
from .forms import ShopForm


def shop_list(request):
    query = request.GET.get('query', '').strip()
    qs = Shop.objects.all()
    if query:
        qs = qs.filter(name__icontains=query)
    return render(request, 'shop/shop_list.html', {
        'shop_list': qs,
        'query': query,
    })

# shop_list = ListView.as_view(model=Shop, paginate_by=20)


def shop_detail(request, pk):
    shop = Shop.objects.get(pk=pk)
    return render(request, 'shop/shop_detail.html', {
        'shop': shop,
    })

# shop_detail = DetailView.as_view(model=Shop)


# def shop_new(request):
#     if request.method == 'POST':  # 'GET', 'POST'
#         # request.GET, request.POST, request.FILES
#         form = ShopForm(request.POST, request.FILES)
#         if form.is_valid():
#             shop = form.save()
#             return redirect('/shop/{}/'.format(shop.pk))
#     else:
#         form = ShopForm()
#     return render(request, 'shop/shop_form.html', {
#         'form': form,
#     })

shop_new = CreateView.as_view(model=Shop, form_class=ShopForm)


def shop_edit(request, pk):
    shop = Shop.objects.get(pk=pk)
    if request.method == 'POST':  # 'GET', 'POST'
        # request.GET, request.POST, request.FILES
        form = ShopForm(request.POST, request.FILES, instance=shop)
        if form.is_valid():
            shop = form.save()
            # return redirect('/shop/{}/'.format(shop.pk))
            return redirect(shop)
    else:
        form = ShopForm(instance=shop)
    return render(request, 'shop/shop_form.html', {
        'form': form,
    })

# shop_edit = UpdateView.as_view(model=Shop, form_class=ShopForm,
#                                success_url='/shop/')


def item_list(request):
    # DB로부터 모든 Item List를 가져올 예정
    qs = Item.objects.all()  # QuerySet 타입
    # 템플릿 파일 위치 : shop/templates/shop/item_list.html
    return render(request, 'shop/item_list.html', {
        'item_list': qs,
    })


def item_detail(request, pk):
    item = Item.objects.get(pk=pk)  # 즉시 DB로부터 Fetch
    return render(request, 'shop/item_detail.html', {
        'item': item,
    })

accounts/templates/accounts/layout.html
{% extends "layout.html" %}

accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}

{% block content %}
    <h2>{{ user }}'s Profile</h2>
{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends "accounts/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" />
    </form>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{ post.title }}</h2>

    {{ post.content }}
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}
{% load bootstrap4 %}

{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% bootstrap_form form %}

        <input type="submit" />
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <table>
        <tbody>
            {% for post in post_list %}
                <tr>
                    <td>{{ post.title }}</td>
                    <td>{{ post.masked_ip }}</td>
                    <td>{{ post.created_at }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url "blog:post_new" %}">New Post</a>
{% endblock %}

pnu/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>PNU's Django</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
    </head>
    <body>
        <a href="{% url 'root' %}">Home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'profile' %}">{{ user }} 프로필</a>
            <a href="{% url 'logout' %}?next={{ request.path }}">로그아웃</a>
        {% else %}
            <a href="{% url 'signup' %}">회원가입</a>
            <a href="{% url 'login' %}?next={{ request.path }}">로그인</a>
        {% endif %}

        <div class="container">
            <div class="col-sm-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

shop/templates/shop/item_detail.html
<h1>{{ item.name }}</h1>

{{ item.desc }}

{{ item.price }}

<hr/>

{{ item.created_at }}

{{ item.updated_at }}

shop/templates/shop/item_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>Item List</h1>

            <table class="table table-bordered table-hover">
            {% for item in item_list %}
                <tr>
                    <td>
                        {# TODO: URL Reverse 기능으로 개선 #}
                        <a href="{% url "shop:item_detail" item.pk %}"></a>
                            {{ item.name }}
                        </a>
                    </td>
                    <td>{{ item.desc }}</td>
                    <td>{{ item.price }}</td>
                    <td>{{ item.created_at }}</td>
                    <td>{{ item.updated_at }}</td>
                </tr>
            {% endfor %}
            </table>

            <a href="#" class="btn btn-primary">New Item</a>
        </div>
    </div>
</div>

shop/templates/shop/layout.html
{% extends "layout.html" %}

shop/templates/shop/shop_detail.html
{% extends "shop/layout.html" %}

{% block content %}
    <div class="card">
        <div class="card-header">
            Shop: {{ shop.name }}
        </div>
        <div class="card-body">
            {% if shop.photo %}
                <img src="{{ shop.photo.url }}" style="max-width: 100%;" />
            {% endif %}

            <!-- <h5 class="card-title">Special title treatment</h5> -->
            <p class="card-text">
                {{ shop.address }}
            </p>
            <p class="card-text">
                {{ shop.desc }}
            </p>
            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
    </div>

    <hr/>
    <a href="{% url 'shop:shop_list' %}" class="btn btn-primary">목록</a>
    <a href="{% url 'shop:shop_edit' shop.pk %}" class="btn btn-success">수정</a>
{% endblock %}

shop/templates/shop/shop_form.html
{% extends "shop/layout.html" %}

{% block content %}
    <h2>New Shop</h2>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" />
    </form>

    {% comment %}
        <form action="" method="GET">
            title: <input type="text" name="title" /><br/>
            content: <textarea name="content"></textarea><br/>
            <input type="submit" value="저장" />
        </form>
    {% endcomment %}
{% endblock %}

shop/templates/shop/shop_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <h1>Shop List</h1>

    <form action="" method="GET">
        <input type="text" name="query" value="{{ query }}" placeholder="검색어를 입력해주세요." />
        <input type="submit" value="검색" class="btn btn-primary" />
    </form>

    <table class="table table-hover table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for shop in shop_list %}
                <tr>
                    <td>
                        <a href="{{ shop.get_absolute_url }}">
                            {{ shop.name }}
                        </a>
                    </td>
                    <td>{{ shop.address }}</td>
                    <td>
                        <a href="{% url "shop:shop_edit" shop.pk %}" class="btn btn-info btn-sm">
                            수정
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{% url 'shop:shop_new' %}" class="btn btn-primary">
        New Shop
    </a>
{% endblock %}